<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="fr_FR">
<context>
    <name>AboutArea</name>
    <message>
        <source>&lt;p&gt;This is a Sokoban game. The purpose of the game is to move the diamonds to the green spots by letting the man push against the diamonds. You move the man using the arrow keys or by clicking/touching the place where the man must move (only horizontal or vertical moves are possible).&lt;/p&gt;&lt;p&gt;Enjoy!&lt;/p&gt;&lt;p&gt;If the screen is small, the buttons in the menu or in the toolbar may not all be visible, in this case the menu and the toolbar can be dragged to make these buttons visible.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Ceci est un jeu Sokoban. Le but du jeu est de déplacer les diamants vers les points verts en faisant l&apos;homme pousser les diamants. Vous déplacez l&apos;homme en utilisant les touches fléchées ou en cliquant/touchant l&apos;endroit ou l&apos;homme doit se déplacer (seuls les déplacements horizontaux ou verticaux sont possibles).&lt;/p&gt;&lt;p&gt;Amusez-vous!&lt;/p&gt;&lt;p&gt;Si l&apos;écran est petit, les boutons dans le menu ou dans la barre d&apos;outils pourraient ne pas tous être visibles, dans ce cas vous pouvez glisser et déposer le menu et la barre d&apos;outils afin de rendre ces boutons visibles.&lt;/p&gt;</translation>
    </message>
    <message>
        <source>&lt;p&gt;This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.&lt;/p&gt;&lt;p&gt;This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.&lt;/p&gt;&lt;p&gt;You should have received a copy of the GNU General Public License along with this program; if not, see &lt;a style=&quot;color: #BBBBEE&quot; href=&quot;http://www.gnu.org/licenses&quot;&gt;http://www.gnu.org/licenses&lt;/a&gt;.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Ce programme est un logiciel libre; vous pouvez le redistribuer et le modifier conformément à la licence « GNU General Public License » telle que publiée à la « Free Software Foundation »; soit la troisième version, soit selon votre convenance n&apos;importe quelle version ultérieure à cette dernière.&lt;/p&gt;&lt;p&gt;Ce programme est distribué dans l&apos;espoir qu&apos;il sera utile, mais SANS GARANTIE AUCUNE; même avec le concept implicite de VALEUR MARCHANDE. Référez-vous pour plus de détails à la « GNU General Public License ».&lt;/p&gt;&lt;p&gt;Vous devriez avoir reçu une copie de la Licence « GNU General Public License » avec ce programme, sinon, voir &lt;a style=&quot;color:#BBBBEE&quot; href=&quot;http://www.gnu.org/licenses&quot;&gt;http://www.gnu.org/licenses&lt;/a&gt;.&lt;/p&gt;</translation>
    </message>
</context>
<context>
    <name>GameView</name>
    <message>
        <source>Game over</source>
        <translation>Jeu terminé</translation>
    </message>
    <message>
        <source>Level %1 won!&lt;br&gt;Press any key or click/touch the screen to continue</source>
        <translation>Niveau %1 gagné!&lt;br&gt;Appuyez sur n&apos;importe quelle touche ou cliquez/touchez l&apos;écran pour continuer</translation>
    </message>
    <message>
        <source>Game won!&lt;br&gt;Press any key or click/touch the screen to start again</source>
        <translation>Jeu gagné!&lt;br&gt;Appuyez sur n&apos;importe quelle touche ou cliquez/touchez l&apos;écran pour recommencer</translation>
    </message>
</context>
<context>
    <name>LevelCollectionArea</name>
    <message>
        <source>Simple Sokoban</source>
        <translation>Sokoban simple</translation>
    </message>
    <message>
        <source>Original levels</source>
        <translation>Niveaux originaux</translation>
    </message>
    <message>
        <source>Extra levels</source>
        <translation>Niveaux supplémentaires</translation>
    </message>
    <message>
        <source>Still more</source>
        <translation>Encore plus</translation>
    </message>
    <message>
        <source>For the kids</source>
        <translation>Pour les enfants</translation>
    </message>
    <message>
        <source>Dimitri and Yorick</source>
        <translation>Dimitri et Yorick</translation>
    </message>
    <message>
        <source>MacTommy Inventions</source>
        <translation>Inventions de MacTommy</translation>
    </message>
    <message>
        <source>Yoshios Autogenerated</source>
        <translation>Autogénérés par Yoshio</translation>
    </message>
</context>
<context>
    <name>MenuPanel</name>
    <message>
        <source>Start New Game</source>
        <translation>Nouveau jeu</translation>
    </message>
    <message>
        <source>Quit</source>
        <translation>Quitter</translation>
    </message>
    <message>
        <source>About</source>
        <translation>À propos</translation>
    </message>
    <message>
        <source>Continue Game</source>
        <translation>Continuer jeu</translation>
    </message>
    <message>
        <source>New Game</source>
        <translation>Nouveau jeu</translation>
    </message>
    <message>
        <source>New</source>
        <translation>Nouveau</translation>
    </message>
    <message>
        <source>Continue</source>
        <translation>Continuer</translation>
    </message>
    <message>
        <source>Choose level collection</source>
        <translation>Choisir collection de niveaux</translation>
    </message>
    <message>
        <source>Level collection</source>
        <translation>Collection de niveaux</translation>
    </message>
    <message>
        <source>Levels</source>
        <translation>Niveaux</translation>
    </message>
</context>
<context>
    <name>ToolBar</name>
    <message>
        <source>Menu</source>
        <translation>Menu</translation>
    </message>
    <message>
        <source>Previous Level</source>
        <translation>Jeu précédent</translation>
    </message>
    <message>
        <source>Next Level</source>
        <translation>Jeu suivant</translation>
    </message>
    <message>
        <source>Zoom In</source>
        <translation type="obsolete">Agrandir</translation>
    </message>
    <message>
        <source>Zoom Out</source>
        <translation type="obsolete">Rétrécir</translation>
    </message>
    <message>
        <source>Level: %1</source>
        <translation>Niveau : %1</translation>
    </message>
    <message>
        <source>Undo</source>
        <translation>Défaire</translation>
    </message>
</context>
</TS>
